import React from "react";
import styled from "styled-components";
import DownloadOutputButton from "./DownloadOuputButton";

const StyledFixedButton = styled.div`
  position: fixed;
  flex-direction: column;
  display: flex;
  bottom: 5px;
  right: 40px;
  background-color: ${props => props.theme.backgroundColors.downloadButtonBlue}; 
  align-items: center;
  justify-content: center;
  padding: 20px;
  border-radius: 4px;
`;

/**
 * Render the position and container of a button that downloads the output result as csv shown on all the plates
 *
 * @param props.plates each plate generated by the minizinc model
 */
const FixedDownloadButton = (props) => {
  return (
    <StyledFixedButton>
      <DownloadOutputButton plates={props.plates} single={false} />
    </StyledFixedButton>
  );
};

export default FixedDownloadButton;
